services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data}
    volumes:
      - postgres_data:${PGDATA:-/var/lib/postgresql/data}
    ports:
      - '${DB_PORT:-5432}:5432'
    networks:
      - app_network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123456}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - app_network
    restart: unless-stopped

  app:
    container_name: nestjs_app_container
    build: ../..
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASS: ${POSTGRES_PASSWORD:-123456}
      DB_NAME: ${POSTGRES_DB:-postgres_db}
      DATABASE_URL: "postgresql://postgres:123456@postgres:5432/postgres_db"
    ports:
        - '4000:4000'
    networks:
      - app_network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
